name: Spark CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy custom code
      run: |
        # Copy code from custom_folder into the source folder
        ls -la src/
        cp -r custom_folder/* src/
        ls -la src/
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Spark environment
      run: |
        # Install Spark and dependencies here
        # You can use Apache Spark's official Docker image or install it manually
        ##docker images
        ##docker pull apache/spark
        ##docker images
        # Example: Download and install Spark manually

    - name: Build and test Spark app
      run: |
        # Build and test your Spark application here
        # Example: sbt clean package
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    
    - name: Deploy to ArgoCD
      run: |
        # Use ArgoCD CLI or API to trigger deployment
        # Example: argocd app sync my-spark-app
        curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
        rm argocd-linux-amd64
        argocd login 54.226.25.98:31218 --username admin --password SojWh5-NBGRCy69G --insecure
        argocd app list
        argocd app sync apache-spark      
